baseURL = "https://coderevue.net/"
languageCode = "en-us"
theme = "archie"

# Header and footer
title = "CodeREVUE.net"
copyright = "CodeREVUE.net"

# Main page listing
summaryLength = 40

# Code Highlight
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "monokai"
