baseURL = "https://coderevue.net/"
languageCode = "en-us"
title = "Code Revue"
copyright = "© Code Revue"
theme = "archie"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mode = "light"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/lurkshark/coderevue"

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
