name: Deploy Node-RED to NearlyFreeSpeech.NET
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rsync and install package on remote server
        env:
          NFSN_HOST: ${{ secrets.NFSN_HOST }}
          NFSN_SSH_KEY: ${{ secrets.NFSN_SSH_KEY }}
          NFSN_USERNAME: ${{ secrets.NFSN_USERNAME_GUZZLE_DIRTY_VODKA }}
        run: |
          eval `ssh-agent`
          ssh-add - <<< ${NFSN_SSH_KEY}
          SOURCE=${GITHUB_WORKSPACE}/202201-node-red-automation/
          DESTINATION=${NFSN_USERNAME}@${NFSN_HOST}:/home/protected
          rsync -zvrh -e 'ssh -o StrictHostKeyChecking=no' ${SOURCE} ${DESTINATION}
          ssh ${NFSN_USERNAME}@${NFSN_HOST} <<EOF
            cd /home/protected && npm install
            nfsn signal-daemon npm term
          EOF
