name: Deploy to NearlyFreeSpeech.NET
on:
  push:
    branches:
      - main
      - xx-deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download and install Hugo package
        run: |
          HUGO_VERSION=0.82.0
          HUGO_DEB=hugo_${HUGO_VERSION}_Linux-64bit.deb
          HUGO_RELEASES=https://github.com/gohugoio/hugo/releases/download/
          HUGO_RELEASE_DEB=${HUGO_RELEASES}v${HUGO_VERSION}/${HUGO_DEB}
          echo ${HUGO_RELEASE}
          wget ${HUGO_RELEASE}
          sudo apt install ./${HUGO_DEB}
      - name: Verify Hugo was installed
        run: hugo --version
