name: Deploy website content to NearlyFreeSpeech.NET
on:
  push:
    branches:
      - main
    paths:
      - 'website-content/**'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download and install Hugo package
        run: |
          HUGO_VERSION=0.82.0
          HUGO_DEB=hugo_${HUGO_VERSION}_Linux-64bit.deb
          HUGO_RELEASES=https://github.com/gohugoio/hugo/releases/download/
          HUGO_RELEASE_DEB=${HUGO_RELEASES}v${HUGO_VERSION}/${HUGO_DEB}
          wget ${HUGO_RELEASE_DEB} && sudo apt install ./${HUGO_DEB}
      - name: Generate Hugo website files
        run: |
          cd ${GITHUB_WORKSPACE}/website-content
          hugo
      - name: Copy generated files to remote server
        env:
          WEBDAV_USER: ${{ secrets.WEBDAV_USER }}
          WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
        run: |
          sudo -v ; curl https://rclone.org/install.sh | sudo bash
          rclone config create fastmail webdav \
            user=${WEBDAV_USER} pass=${WEBDAV_PASSWORD} \
            url=https://myfiles.fastmail.com vendor=fastmail \
            --non-interactive
          rclone copy ${GITHUB_WORKSPACE}/website-content/public/ fastmail:/coderevue/
